{
 "title": "ISP",
 "description": "A real-time monitoring of your Internet Service Protocol.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Download & Upload Speeds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  download AS \"Speed Download (MB/s)\"\nFROM isp\nORDER BY hour"
    },
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  upload AS \"Speed Upload (MB/s)\"\nFROM isp\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  download\nFROM isp\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  latency AS \"Latency (ms)\"\nFROM isp\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  upload\nFROM isp\nORDER BY hour"
    }
   ]
  }
 ]
}