{
 "title": "SNMP Linux",
 "description": "A real-time monitoring of your Linux devices.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SELECT DISTINCT hostname FROM snmp_linux order by hostname"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Loads Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  load1 AS \"CPU Usage over Last Minute (%)\",\n  load5 AS \"CPU Usage over 5 Last Minutes (%)\",\n  load15 AS \"CPU Usage over 15 Last Minutes (%)\"\nFROM snmp_linux\nWHERE \n  hostname = '$Host'\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Ram Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  ram_total AS \"Total RAM Space (GB)\",\n  (ram_total - ram_free) AS \"Used Ram Space (GB)\"\nFROM snmp_linux\nWHERE \n  hostname = '$Host'\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Disk Stats",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  (100 - disk_percent) AS \"Free Disk Space (%)\"\nFROM snmp_linux\nWHERE hostname='$Host'\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Disk Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  disk_total AS \"Total Disk Space (GB)\",\n  disk_used AS \"Used Disk Space (GB)\"\nFROM snmp_linux\nWHERE hostname='$Host'\nORDER BY hour"
    }
   ]
  }
 ]
}