{
 "title": "SNMP Windows",
 "description": "A real-time monitoring of your Windows devices.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SELECT DISTINCT hostname FROM snmp_windows order by hostname"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  cpu_usage AS \"CPU Usage over Last Minute (%)\"\nFROM snmp_windows\nWHERE\n  hostname = '$Host'\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Ram Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  ram_total as \"Total Ram Space (GB)\",\n  ram_used as \"Used Ram Space (GB)\"\nFROM snmp_windows\nWHERE\n  hostname = '$Host'\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Disk Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  disk_total AS \"Total Disk Space (GB)\",\n  disk_used AS \"Used Disk Space (GB)\"\nFROM snmp_windows\nWHERE\n  hostname = '$Host'\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Disk Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS \"time\",\n  (100 - disk_percent) AS \"Free Disk Space (%)\"\nFROM snmp_windows\nWHERE\n  hostname = '$Host'\nORDER BY hour"
    }
   ]
  }
 ]
}